stages:
  - lint
  - release

include:
  - project: 'sds-dev/releases'
    ref: main
    file: 'releases.yml'

lint-cli:
  stage: lint
  tags:
    - sds
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes:
      paths:
        - sd_connect_s3_migrate_cli/**/*
      compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script: |
    echo "Placeholder for linting cli"
    echo "tox"

lint-format-gui:
  stage: lint
  tags:
    - docker-exec
  # Using image which has node stuff preinstalled
  image: $ARTIFACTORY_SERVER/sds/sdd-common-ci:2026.8.0
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes:
      paths:
        - sd_connect_s3_migrate_gui/**/*
      compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script: |
    echo "Linting gui with eslint"
    cd sd_connect_s3_migrate_gui
    npm install
    npm run lint-format

update-versions-dryrun:
  extends: .update-versions-dryrun
  variables:
    UPDATE_VERSION_FILES_LIST: "sd_connect_s3_migrate_gui/package.json;sd_connect_s3_migrate_cli/__init__.py"
    VERSION_UPDATE_INDICATOR: "version"

update-versions:
  extends: .update-versions
  variables:
    UPDATE_VERSION_FILES_LIST: "sd_connect_s3_migrate_gui/package.json;sd_connect_s3_migrate_cli/__init__.py"
    VERSION_UPDATE_INDICATOR: "version"

release-job:
  extends: .automated-release
  release:
    description: $(cat release_changes.md)
