stages:
  - lint
  - release

include:
  - project: 'sds-dev/releases'
    ref: main
    file: 'releases.yml'

lint-cli:
  stage: lint
  tags:
    - sds
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes:
      paths:
        - sd_connect_s3_migrate_cli/**/*
      compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script: |
    echo "Placeholder for linting cli"
    echo "tox"

lint-gui:
  stage: lint
  tags:
    - docker-exec
  # Using image which has node stuff preinstalled
  image: $ARTIFACTORY_SERVER/sds/sdd-golang-common-ci
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes:
      paths:
        - sd_connect_s3_migrate_gui/**/*
      compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script: |
    echo "Linting gui with eslint"
    cd sd_connect_s3_migrate_gui
    npm install
    npm run lint

release-job:
  extends: .automated-release
  release:
    description: $(cat release_changes.md)
