[tox]
envlist = flake8, bandit, mypy, black
skipdist = True

[flake8]
max-line-length = 80
select = C,E,F,W,B,B950
ignore = E203,E501,W503,ANN101
exclude = .git/, ./venv/, ./.tox/, build/, sd_connect_s3_migrate_cli.egg-info/

[testenv:bandit]
skip_install = True
deps = bandit
commands = bandit -r ./sd_connect_s3_migrate_cli

[testenv:flake8]
skip_install = True
deps =
    flake8
    flake8-docstrings
    flake8-annotations
commands = flake8 sd_connect_s3_migrate_cli

[testenv:mypy]
skip_install = true
deps =
    -rrequirements.txt
    mypy
    types-certifi
    types-aiofiles
# Mypy fails if 3rd party library doesn't have type hints configured.
# Alternative to ignoring imports would be to write custom stub files, which
# could be done at some point.
commands = mypy --ignore-missing-imports --no-namespace-packages sd_connect_s3_migrate_cli

[testenv]
deps =
    -rrequirements.txt

[testenv:black]
skip_install = true
deps =
    black
commands = black sd_connect_s3_migrate_cli -l 90 --check

[gh-actions]
python =
    3.12: flake8, bandit, black, mypy
