name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ steps.vars.outputs.tag }} of Swift to S3 Migration Tool for SD Connect.


  build-electron:
    name: "Create electron release assets"
    needs: "create-release"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14, windows-2022, windows-11-arm]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
        working-directory: "./sd_connect_s3_migrate_gui"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache-dependency-path: "./sd_connect_s3_migrate_gui"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      - name: Install system deps (Linux)
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenjp2-tools \
            libasound2 \
            libnss3 \
            libxss1 \
            appstream \
            desktop-file-utils \
            fakeroot \
            rpm \
            libarchive-tools \
            build-essential \
            snapd
      
      - name: Install snapcraft 7 for core18 (Linux)
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run : |
          sudo snap install snapcraft --classic --channel 7.x/stable
          sudo snap install multipass --classic

      - name: Build application
        run: |
          if [ "${{ matrix.os }}" == "windows-2022" ] || [ ${{ matrix.os }} == "windows-11-arm" ]; then
            npm run make:win32
          elif [ ${{ matrix.os }} == "macos-14" ]; then
            npm run make:macos
          else
            npm run make:linux
          fi

      - name: Upload build artifacts using forge publish
        run: |
          npm run publish

      - name: Upload release assets
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: sd_connect_s3_migrate_gui/out/make/**
          fail_on_unmatched_files: true

  build-appimage:
    name: "Create Linux AppImage release assets for CLI script"
    needs: "create-release"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
        working-directory: ./sd_connect_s3_migrate_bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system deps (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            tar \
            jq \
            unzip

      - name: Build application
        run: |
          ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-build-${{ matrix.os }}
          path: |
            sd_connect_s3_migrate_bash/*.AppImage

      - name: Upload release assets
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: sd_connect_s3_migrate_bash/*.AppImage
          fail_on_unmatched_files: true
